#
###################################
# Site wide configuration
####################################
#
title: Pythad Blog
email: ovd4mail@gmail.com
description: Blog about Python, Django and web-development
url: https://pythad.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Kyiv
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Vlad Ovchynnykov
  avatar: avatar.jpg
  job: "Python developer"
  bio: "Blog about Python, Django and web-development"
  email: ovd4mail@gmail.com
  disqus-shortname: pythadgithubio
  twitter: pythady
  facebook: #username
  google:
    plus: #username
    analytics: UA-71320445-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: pythad
  gitlab: #username
  stackoverflow: 3832802/pythad
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
